### ISSUE TITLE
ModuleNotFoundError: No module named 'microstrain_inertial_rqt.utils' unless using 2.5.0

### ISSUE THREAD

**Issue by lucasw** [LORD-MicroStrain/microstrain_inertial_driver_common#50]
```
roslaunch microstrain_inertial_rqt quickview.launch
...
RosPluginProvider.load(microstrain_inertial_rqt/Quickview) exception raised in __builtin__.__import__(microstrain_inertial_rqt.quickview, [Quickview]):
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 79, in load
    module = __builtin__.__import__(
  File "/opt/ros/noetic/lib/python3/dist-packages/microstrain_inertial_rqt/quickview.py", line 3, in <module>
    from .utils.constants import _MICROSTRAIN_ROS_VERISON
ModuleNotFoundError: No module named 'microstrain_inertial_rqt.utils'

PluginManager._load_plugin() could not load plugin "microstrain_inertial_rqt/Quickview":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 61, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 90, in load
    raise e
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 79, in load
    module = __builtin__.__import__(
  File "/opt/ros/noetic/lib/python3/dist-packages/microstrain_inertial_rqt/quickview.py", line 3, in <module>
    from .utils.constants import _MICROSTRAIN_ROS_VERISON
ModuleNotFoundError: No module named 'microstrain_inertial_rqt.utils'
```

I did a source checkout and went back to `2.5.0` and that looks to work

These are the apt installed versions:

```
ii  ros-noetic-microstrain-inertial-driver          3.0.1-1focal.20230216.003402                                        amd64        The ros_mscl package provides a driver for the LORD/Microstrain inertial products.
ii  ros-noetic-microstrain-inertial-driver-dbgsym   3.0.1-1focal.20230216.003402                                        amd64        debug symbols for ros-noetic-microstrain-inertial-driver
ii  ros-noetic-microstrain-inertial-examples        3.0.1-1focal.20230215.233316                                        amd64        Example listener for Parker LORD Sensing inertial device driver ros_mscl (C++).
ii  ros-noetic-microstrain-inertial-examples-dbgsym 3.0.1-1focal.20230215.233316                                        amd64        debug symbols for ros-noetic-microstrain-inertial-examples
ii  ros-noetic-microstrain-inertial-msgs            3.0.1-1focal.20230210.214240                                        amd64        A package that contains ROS message corresponding to microstrain message types.
ii  ros-noetic-microstrain-inertial-rqt             3.0.1-1focal.20230215.234432                                        amd64        The microstrain_inertial_rqt package provides several RQT widgets to view the status of Microstrain devices
```

(and now that I look I see this is the wrong repo to report this, it should be https://github.com/LORD-MicroStrain/microstrain_inertial or [microstrain_inertial_rqt_common](https://github.com/LORD-MicroStrain/microstrain_inertial_rqt_common))

**Comment by robbiefish** [comment]
This should be fixed in the most recent 3.0.0 and 4.0.0 releases
